INSERT INTO skill(skill_id, skill_type) VALUES

                                            (gen_random_uuid(), 'Woodworking'),
                                            (gen_random_uuid(), 'Metalworking'),
                                            (gen_random_uuid(), 'General Fabrication'),
                                            (gen_random_uuid(), 'Welding'),
                                            (gen_random_uuid(), 'Furniture Building'),
                                            (gen_random_uuid(), 'Resin Crafting'),
                                            (gen_random_uuid(), 'Plasma Cutting'),
                                            (gen_random_uuid(), 'Machining'),
                                            (gen_random_uuid(), 'Laser Cutting'),
                                            (gen_random_uuid(), '3D Printing'),
                                            (gen_random_uuid(), '3D Modeling'),
                                            (gen_random_uuid(), 'CNC'),
                                            (gen_random_uuid(), 'Large Format Printing'),
                                            (gen_random_uuid(), 'Sticker Making'),
                                            (gen_random_uuid(), 'Jewelry Making'),
                                            (gen_random_uuid(), 'Graphic Design'),
                                            (gen_random_uuid(), 'Photography'),
                                            (gen_random_uuid(), 'Rapid Prototyping'),
                                            (gen_random_uuid(), 'Ceramics'),
                                            (gen_random_uuid(), 'Stained Glass'),
                                            (gen_random_uuid(), 'Glassblowing'),
                                            (gen_random_uuid(), 'Textiles'),
                                            (gen_random_uuid(), 'Painting'),
                                            (gen_random_uuid(), 'Murals'),
                                            (gen_random_uuid(), 'Mosaics'),
                                            (gen_random_uuid(), 'Sculpture'),
                                            (gen_random_uuid(), 'Illustration'),
                                            (gen_random_uuid(), 'Animation'),
                                            (gen_random_uuid(), 'Sewing');